### ISSUE TITLE
Is this usable?

### ISSUE THREAD

**Issue by rudizl** [StyraHem/pyTesy#1]
Sorry for the dumb question, I`m new to all this things. How can I use this with HA installed on Raspberry Pi 4?
installed it via "pip3 install pyTesy", but my knowledge end here :(

**Comment by rudizl** [comment]
A little update:
I found, that the component was installed in custom_components/pytesy folder. Also from comments to pyShelly component I`ve managed to add something like this in configuartion.yaml:
```
# Tesy
pytesy:
  email: my.email@gmail.com
  password: my.password
 
```
The error after restarting HA is:
`Invalid config
The following integrations and platforms could not be set up:

pytesy
Please check your config.`

:(

**Comment by hakana** [comment]
It is nothing that is ready to use.

**Comment by rudizl** [comment]
That is so sad... Do you have any plans to develop the component any further?

**Comment by hakana** [comment]
What Tesy device do you have?

**Comment by rudizl** [comment]
Water heater .

**Comment by abixbg** [comment]
If you just want to get information without controlling it there is a way with curl. The only thing you need is your token and sessionID. Then you can get JSON with the heater status. Home assistant has templates that parse that into sensors. @hakana solution is way cleaner and flexible with Python rather than bash script.

**Comment by rudizl** [comment]
@abixbg, it will be great to control it, but if there is no way to do that... Also those curl and parse things sounds to me like foreign language :)

**Comment by abixbg** [comment]
Unfortunately my solution is also not "ready to use" and you need to have some knowledge about advanced Home Assistant stuff like templating. Frankly I planned to make a guide or even HA integration but Tesy's "smart" controller disappointed me with how unreliable it is. On random intervals the temperature sensor gives random temperature (usually 8-20C* even on the physical display! ) and the heater just turns on HEATING for couple minutes.

**Comment by rudizl** [comment]
Well, I`m not very satisficed with the WH too, but  I have it since 1 or 2 years and can`t throw it away :) There are some disconnections from network, that can be fixed only with complete power off...

Anyway, I`ll be very happy if someone can build a component for dummies:)

**Comment by abixbg** [comment]
I DM you. Lets not bloat @hakana's git *cheers*

**Comment by hakana** [comment]
I just test what I have and locally and it working for reading current temperature, set a new temperature, and turn it on/off.

I have committed the latest version, you find it here:
https://github.com/StyraHem/TesyForHASS/tree/master/custom_components/tesy

You can try to copy the files under **tesy** in your custom_components and see if it works for you also.

config.yaml
```yaml
tesy:
  username: "your@email.address"
  password: "your_password"
```

**Comment by rudizl** [comment]
Thank you. I`ve copied the files. Now I see Tesy in Integrations, but nothing more. There is an error:
```
Log Details (ERROR)
Logger: homeassistant.core
Source: custom_components/tesy/__init__.py:102
First occurred: 16:15:03 (1 occurrences)
Last logged: 16:15:03

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/tesy/__init__.py", line 99, in start_up
    from .pytesy import PyTesy
ModuleNotFoundError: No module named 'custom_components.tesy.pytesy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tesy/__init__.py", line 102, in start_up
    from pyTesy import pyTesy
ModuleNotFoundError: No module named 'pyTesy
```

**Comment by abixbg** [comment]
You should also place pyTESY library in the custom _components folder. I can confirm it worked for me. At least I got water_heater entity in HA.

**Comment by hakana** [comment]
Ok, normally pyTesy should be downloaded automatically, but maybe it not working.

**Comment by rudizl** [comment]
I`ve managed to install the component properly. 

![1](https://user-images.githubusercontent.com/5582186/80726244-d5240f00-8b0c-11ea-9550-c24bb92a9a82.PNG)

![2](https://user-images.githubusercontent.com/5582186/80726267-db19f000-8b0c-11ea-9683-b01b84d682a1.PNG)

The strangest part is, that I can`t change the  "target temp", witch I presume should switch the heater on if the chosen number is bigger than current temperature?
And the second thing- what kind of card can I use for this entity?  

Thank you

**Comment by abixbg** [comment]
1. I think for that to work you should set the heater to [Manual] because otherwise the heater ignores "target_temp" and it uses one of its internal algorithms. 
2. You can use it on any card but you still have to wait for custom lovelace card if you exect to look nice. HA's internal water_heater integration is very limited. You can also split all custom attributes to simple sensors and switches with templating, but that's the advanced HA stuff I mentioned before.

Keep in mind that's work in progress integration and the functionality is very limited atm.

**Comment by rudizl** [comment]
Thank you both.
I`m learning HA, installing sensors, switches etc., so... 

Thank You again.

**Comment by hakana** [comment]
@rudizl You are welcome and thanks for the beer!

**Comment by KPCKPCKPC** [comment]
dear hakana,

First thanks for your nice program. I get an error message when I try to change the temperature. Can you help me with that?

Logger: homeassistant.util.async_
Source: util/async_.py:131
First occurred: 21:33:45 (1 occurrences)
Last logged: 21:33:45

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for tesy doing I/O at custom_components/tesy/pytesy/__init__.py, line 97: resp = self._conn.post(TESY_URL + url)

greetings Jos

**Comment by kbenni** [comment]
Hello,
i have same issue as @abixbg
I installed the tesy and pyTesy component to HA custom_components, both components are successfully loaded (manifest file was updated) but I can see this in logs and i dont know what else can i try

Logger: homeassistant
Source: custom_components/tesy/__init__.py:102
Integration: Teasy water heate (documentation)
First occurred: 12:28:24 (1 occurrences)
Last logged: 12:28:24

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/tesy/__init__.py", line 99, in start_up
    from .pytesy import PyTesy
ModuleNotFoundError: No module named 'custom_components.tesy.pytesy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tesy/__init__.py", line 102, in start_up
    from pyTesy import pyTesy
ModuleNotFoundError: No module named 'pyTesy'

but it was loaded based on logs:
2021-12-27 12:27:50 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration pyTesy which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

thank you

**Comment by ValeriGYordanov** [comment]
Is this still working?
Do you have any issues with it?

I tried almost everything you were saying but ended up on 
"Integration error: pyTesy - Integration 'pyTesy' not found."
when adding it to the config.yaml
or of course
Integration error: tesy - Integration 'tesy' not found.

Both pyTesy and tesy projects are in the community folder.

**Comment by rudizl** [comment]
No, it`s not working anymore.

**Comment by ValeriGYordanov** [comment]
Are you aware of any alternative?
Thanks for the fast response.

**Comment by rudizl** [comment]
No, I've checked earlier the errors in my log and changed in __init__.py this:
`_LOGGER = logging.getLogger(NAME)
TESY_URL = "https://www.mytesy.com/"`
to this:
`_LOGGER = logging.getLogger(NAME)
TESY_URL = "https://www.mytesy.com/v3/#login"`

At least now I don`t have errors, but still not working.

**Comment by ValeriGYordanov** [comment]
I can't get it working even to this step, as far as I remember (Because I tried almost like 50 different variants of tesy integration). I end up on the config.yaml with the error that tesy: integration no found.

Anyway since this doesn't work anymore it's pointless to spam here.
I think I found something that looks promising but I don't have time to test it now, I will probably try it this weekend.

If anyone else has experience with it, it would be great to share.
https://github.com/william-sy/TesyLocal
https://community.home-assistant.io/t/new-electric-water-heater-boiler-integrated-with-ha/424716/10

**Comment by rudizl** [comment]
Nice, I`ve added it and it`s working greath.

**Comment by acfnews** [comment]
Hi Hakan, would be really great if we can combine both of your work and Williams, and create a real integration in HA, using the local API of the Tesy devices. Would you consider rewriting/update your code so it starts using the local API isof the cloud?

Currently I am not owning such a water heater yet, but planning on buying one as it is one of the few with a local API.
