### ISSUE TITLE
tesy cloud update - lib is working no more.

### ISSUE THREAD

**Issue by motababravo** [StyraHem/pyTesy#2]
Yes It was usable thru the cloud. Not so much now after the latest tesy cloud rebrand.

**Comment by rudizl** [comment]
Hi, is there any chance, that you can fix this?

```
This error originated from a custom integration.

Logger: root
Source: custom_components/tesy/pytesy/__init__.py:108
Integration: Tesy water heater (documentation)
First occurred: 15:09:15 (1 occurrences)
Last logged: 15:09:15

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/config/custom_components/tesy/pytesy/__init__.py", line 80, in poll_thread
    self.poll()
  File "/config/custom_components/tesy/pytesy/__init__.py", line 108, in poll
    for key, value in data['device'].items():
KeyError: 'device'
```
Thank you .
